version: '3.5'

services:

  d3-btc-registration:
    image: nexus.iroha.tech:19002/d3-deploy/btc-registration:develop
    container_name: d3-btc-registration
    ports:
      - 8086:8086
    environment:
      WAIT_HOSTS: d3-rmq:5672, d3-iroha:50051
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS_TIMEOUT: 60
    volumes:
      - ../configs:/opt/notary/configs
      - ../deploy/iroha/keys:/opt/notary/deploy/iroha/keys
    networks:
      - d3-network

  d3-btc-dw-bridge:
    image: nexus.iroha.tech:19002/d3-deploy/btc-dw-bridge:develop
    container_name: d3-btc-dw-bridge
    ports:
      - 7074:7074
    environment:
      WAIT_HOSTS: d3-rmq:5672, d3-iroha:50051
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS_TIMEOUT: 60
    volumes:
      - ../configs:/opt/notary/configs
      - ../deploy/bitcoin:/opt/notary/deploy/bitcoin
      - ../deploy/iroha/keys:/opt/notary/deploy/iroha/keys
    depends_on:
      - d3-btc-address-generation
      - d3-btc-registration
    networks:
      - d3-network

  d3-btc-address-generation:
    image: nexus.iroha.tech:19002/d3-deploy/btc-address-generation:develop
    container_name: d3-btc-address-generation
    ports:
      - 7071:7071
    environment:
      WAIT_HOSTS: d3-rmq:5672, d3-iroha:50051
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS_TIMEOUT: 60
    volumes:
      - ../configs:/opt/notary/configs
      - ../deploy/bitcoin:/opt/notary/deploy/bitcoin
      - ../deploy/iroha/keys:/opt/notary/deploy/iroha/keys
    networks:
      - d3-network

networks:
  d3-network:
