version: '3.5'

services:

  d3-btc-registration:
    image: nexus.iroha.tech:19002/d3-deploy/btc-registration:develop
    container_name: d3-btc-registration
    restart: on-failure
    ports:
      - 8086:8086
    environment:
      WAIT_HOSTS: d3-iroha:50051
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS_TIMEOUT: 60
    networks:
      - d3-network

  d3-btc-dw-bridge:
    image: nexus.iroha.tech:19002/d3-deploy/btc-dw-bridge:develop
    container_name: d3-btc-dw-bridge
    restart: on-failure
    ports:
      - 7074:7074
    environment:
      WAIT_HOSTS: d3-rmq:5672, d3-iroha:50051
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS_TIMEOUT: 60
    volumes:
      - ../deploy/bitcoin:/deploy/bitcoin
    depends_on:
      - d3-btc-node0
      - d3-btc-address-generation
      - d3-btc-registration
    networks:
      - d3-network

  d3-btc-address-generation:
    image: nexus.iroha.tech:19002/d3-deploy/btc-address-generation:develop
    container_name: d3-btc-address-generation
    restart: on-failure
    ports:
      - 7071:7071
    volumes:
      - ../deploy/bitcoin:/deploy/bitcoin
    networks:
      - d3-network

  # bitcoin
  d3-btc-node0:
    image: kylemanna/bitcoind:latest
    container_name: d3-btc-node0
    volumes:
      - ../deploy/bitcoin/regtest/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
    entrypoint:
      - bitcoind
      - -deprecatedrpc=generate
    ports:
      - 8332:8332
      - 18333:18333
      - 18444:18444
    networks:
      - d3-network

networks:
  d3-network:
