version: '3.5'

services:
  d3-iroha:
    ports:
      - 50051:50051
    networks:
      - d3-network
  d3-btc-node0:
    ports:
      - 8332:8332
      - 18333:18333
      - 18444:18444
    networks:
      - d3-network
